name: Continuous Integration

on:
  push:
    branches:
      - main
      - jenk
  workflow_dispatch:

jobs:
  my_first_job:
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

     

